name: Deploy Next.js site to Cloudflare Pages

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    environment:
      name: cloudflare
      url: ${{steps.deploy.outputs.deployment-url}}
    name: Publish to Cloudflare Pages
    steps:
      - uses: actions/checkout@v4
      - uses: docker://jekyll/jekyll:latest
        with:
          entrypoint: /github/workspace/bin/build.sh
      - name: Publish to Cloudflare Pages
        id: deploy
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 62758afcaaf5e929beeac70e72312bc6
          wranglerVersion: "3"
          command: pages deploy _site --project-name coltonenglish --commit-dirty=true
